apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-spot
  labels:
    kops.k8s.io/cluster: api.internal.fawry.example.com
spec:
  role: Node
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  minSize: 2
  maxSize: 5
  subnets:
    - eu-west-1a
    - eu-west-1b
    - eu-west-1c
  nodeLabels:
    lifecycle: Spot
  mixedInstancesPolicy:
    instancesDistribution:
      onDemandBase: 0
      onDemandAboveBase: 0
      spotAllocationStrategy: capacity-optimized-prioritized
    instances:
    - t3.medium
    - t3a.medium
    - t3.small
    - t3a.small
    overrides:
    - instanceType: t3.medium
      weightedCapacity: "2"
    - instanceType: t3a.medium
      weightedCapacity: "2"
    - instanceType: t3.small
      weightedCapacity: "1"
    - instanceType: t3a.small
      weightedCapacity: "1"
