apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"] 
      resources:
        requests:
          storage: 5Gi
