apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage 
    spec:
      resources:
        requests:
          storage: 5Gi
  template:
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            memory: "2Gi" 
          requests:
            memory: "1Gi"   
