apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      resources:
        requests:
          storage: 1Gi
  template:
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "512Mi"
